FROM jenkins/jenkins:2.401.3-jdk11

USER jenkins
RUN jenkins-plugin-cli --plugins blueocean:1.27.11 build-timestamp:1.0.3 timestamper:1.17 pollscm:1.3.1 github-api

USER root
ENV FLUENTD_HOST "fluentd"
ENV FLUENTD_PORT "24224"
ENV JAVA_OPTS -Djenkins.install.runSetupWizard=false
ENV JENKINS_URL "http://jenkins:10000"
ENV ACCESS_KEY ${ACCESS_KEY}
ENV SECRET_KEY ${SECRET_KEY}

# Instalação de Python e pip
RUN apt update && \
    apt install -y python3 python3-pip

# Copiar dependências do Python e instalar
COPY ./requirements.txt requirements.txt
RUN pip3 install --no-cache-dir -r requirements.txt || true

# Copiar scripts Groovy para configuração Jenkins
COPY jenkins/1-configureJenkins.groovy /usr/share/jenkins/ref/init.groovy.d/1-configureJenkins.groovy
COPY jenkins/2-addAccessKeys.groovy /usr/share/jenkins/ref/init.groovy.d/2-addAccessKeys.groovy
