FROM python:3.9-slim-buster

# Define o diretório de trabalho
WORKDIR /usr/src/app

# Instala as dependências necessárias, incluindo MLflow, boto3 e AWS CLI
RUN pip install awscli==1.24.7 boto3==1.23.7 mlflow==1.30.0 protobuf==3.20.1

# Expõe a porta do servidor MLflow
EXPOSE 5000

# Define variáveis de ambiente para acesso ao S3
ENV MLFLOW_S3_ENDPOINT_URL=${MLFLOW_S3_ENDPOINT_URL}
ENV AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
ENV AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}

# Cria um ponto de montagem para persistência de dados do MLflow
VOLUME /mnt/mlflow

# Comando para iniciar o MLflow Server
ENTRYPOINT ["mlflow", "server", "-h", "0.0.0.0", "-p", "5000", "--default-artifact-root", "s3://cd4ml-ml-flow-bucket/", "--backend-store-uri", "/mnt/mlflow"]
